abc=('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z')
print('='*30)
print('Primeiras 5 letras',abc[0:5])
print('='*30)
print('ultimas 4 letras',abc[-4:])
print('='*30)
print('abc em ordem alfabetica',(sorted(abc)))
print('='*30)
letra=str(input(f'Digite uma letra para saber a sua posição no alfabeto: ')).upper()
print('='*30)
print(f'A letra {letra} está na {abc.index(letra)+1}° posição')
