n=input('digite algo: ')
print('Otipo primitivo de ', n, 'é', type(n))
print(n, 'é um espaço? ', n.isspace())
print(n,'é um número? ', n.isnumeric())
print(n, 'é uma letra? ', n.isalpha())
print(n, 'é alfanumérico?', n.isalnum())
print(n, 'Está em maiusculas? ', n.isupper())
print(n, 'Está em minusculas? ', n.islower())
print(n, 'Está captalizada?', n.istitle())
